---
- name: 1.系统初始化
  gather_facts: true
  hosts: all
  roles:
    - init
  tags: init 

- name: 2.K8S初始化
  gather_facts: true
  hosts: k8s
  roles:
    - common
  tags: common 

- name: 3.安装Nfs
  gather_facts: true
  hosts: master[0]
  roles:
    - nfs
  tags: nfs

- name: 4.部署Docker
  gather_facts: true
  hosts: k8s 
  roles:
    - docker 
  tags: docker

- name: 5.部署Keepalived高可用
  gather_facts: true
  hosts: ha
  roles:
    - ha
  tags: ha

- name: 6.部署Nginx负载均衡
  gather_facts: true
  hosts: ha
  roles:
    - lb
  tags: lb

- name: 7.部署ETCD
  gather_facts: true
  hosts: etcd
  roles:
    - etcd
  tags: etcd

- name: 8.部署K8S Master01
  gather_facts: true
  hosts: master[0],etcd
  roles:
    - master
  tags: master

- name: 9.部署额外K8S Master
  gather_facts: true
  hosts: master[1:]
  roles:
    - joinmaster
  tags: joinmaster

- name: 10.部署K8S Node
  gather_facts: true
  hosts: node
  roles:
    - node
  tags: node

- name: 11.部署插件
  gather_facts: true
  hosts: master[0]
  roles:
    - plugin
  tags: plugin
