---
- name: 1.系统初始化
  gather_facts: true
  hosts: all
  roles:
    - init
  tags: init 

- name: 2.K8S初始化
  gather_facts: true
  hosts: k8s
  roles:
    - common
  tags: common 

- name: 3.部署Docker
  gather_facts: true
  hosts: k8s 
  roles:
    - docker 
  tags: docker

- name: 4.部署ETCD
  gather_facts: true
  hosts: etcd
  roles:
    - etcd
  tags: etcd

- name: 5.部署K8S Master
  gather_facts: true
  hosts: master[0],etcd
  roles:
    - master
  tags: master

- name: 6.部署K8S Node
  gather_facts: true
  hosts: node
  roles:
    - node
  tags: node

- name: 7.部署插件
  gather_facts: true
  hosts: master
  roles:
    - plugin
  tags: plugin
