---
- name: 1.系统初始化
  gather_facts: false
  hosts: all
  roles:
    - init
  tags: init 

- name: 2.K8S初始化
  gather_facts: false
  hosts: k8s
  roles:
    - common
  tags: common 

- name: 3.部署Docker
  gather_facts: false
  hosts: k8s 
  roles:
    - docker 
  tags: docker

- name: 4.部署K8S Master
  gather_facts: false
  hosts: master
  roles:
    - master
  tags: master

- name: 5.部署K8S Node
  gather_facts: false
  hosts: node
  roles:
    - node
  tags: node

- name: 6.部署插件
  gather_facts: false
  hosts: master
  roles:
    - addons
  tags: addons
