---
- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 配置K8S的yum源
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/

#- name: 安装kubelet kubeadm kubectl
#  shell: "yum install -y kubelet-{{ kube_version }} kubeadm-{{ kube_version }} kubectl-{{ kube_version }} --disableexcludes=kubernetes"

- name: 安装kubelet kubeadm kubectl v2
  package:
    name:
      - "kubelet-{{ kube_version }}"
      - "kubeadm-{{ kube_version }}"
      - "kubectl-{{ kube_version }}"
    state: present

- name: 启动kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: 重置k8s系统
  shell: "kubeadm reset -f"

#- name: 分发 images 脚本
#  template: src=node-pull-images.sh.j2 dest={{ tmp_dir }}/node-pull-images.sh mode=u+x

#- name: 获取镜像
#  shell: /bin/bash {{ tmp_dir }}/node-pull-images.sh

- name: 分发join脚本
  copy:
    src: "{{ tmp_dir }}/node-join.sh"
    dest: "{{ tmp_dir }}/node-join.sh"
    mode: '0755'

- name: 加入集群
  ignore_errors: yes
  shell: "/bin/bash {{ tmp_dir }}/node-join.sh >/dev/null 2>&1"
