---
- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 配置K8S的yum源
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/

#- name: 安装kubelet kubeadm kubectl
#  shell: "yum install -y kubelet-{{ kube_version }} kubeadm-{{ kube_version }} kubectl-{{ kube_version }} --disableexcludes=kubernetes"

- name: 安装kubelet kubeadm kubectl v2
  package:
    name:
      - "kubelet-{{ kube_version }}"
      - "kubeadm-{{ kube_version }}"
      - "kubectl-{{ kube_version }}"
    state: present

- name: 启动kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes    

- name: 添加运行权限1
  shell: "mkdir -p $HOME/.kube"

- name: 添加允许权限2
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "$HOME/.kube/config"
    owner: root
    group: root
    mode: '0600'

- name: 设置kubectl自动补全
  lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - "source <(kubectl completion bash)"

- name: 重置k8s系统
  shell: "kubeadm reset -f"

#- name: 分发 images 脚本
#  template: src=master-pull-images.sh.j2 dest={{ tmp_dir }}/master-pull-images.sh mode=u+x

#- name: 获取镜像
#  shell: /bin/bash {{ tmp_dir }}/master-pull-images.sh

- name: 分发join脚本
  copy:
    src: "{{ tmp_dir }}/master-join.sh"
    dest: "{{ tmp_dir }}/master-join.sh"
    mode: '0755'

- name: 加入集群
  ignore_errors: yes
  shell: "/bin/bash {{ tmp_dir }}/master-join.sh >/dev/null 2>&1"
