---
- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 配置K8S的yum源
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/

- name: 刷新yum源
  shell: "yum clean all; yum makecache fast -y"

#- name: 安装kubelet kubeadm kubectl
#  shell: "yum install -y kubelet-{{ kube_version }} kubeadm-{{ kube_version }} kubectl-{{ kube_version }} --disableexcludes=kubernetes"

- name: 安装kubelet kubeadm kubectl v2
  package:
    name:
      - "kubelet-{{ kube_version }}"
      - "kubeadm-{{ kube_version }}"
      - "kubectl-{{ kube_version }}"
    state: present

- name: 启动kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: 设置kubectl自动补全
  lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - "source <(kubectl completion bash)"

#- name: 生效配置
#  shell: "source ~/.bashrc"
#  ignore_errors: yes

#- name: 分发 images 脚本
#  template: src=master-pull-images.sh.j2 dest={{ tmp_dir }}/master-pull-images.sh mode=u+x

#- name: 获取镜像
#  shell: /bin/bash {{ tmp_dir }}/master-pull-images.sh

- name: 重置k8s系统
  shell: "kubeadm reset -f"

- name: 分发init配置
  template: src=kubeadm-init.conf.j2 dest={{ tmp_dir }}/kubeadm-init.conf

- name: kubeadm init
  shell: "kubeadm init --config={{ tmp_dir }}/kubeadm-init.conf --upload-certs > {{ tmp_dir }}/token.txt"

- name: 添加运行权限
  shell: "mkdir -p $HOME/.kube; sudo cp -pf /etc/kubernetes/admin.conf $HOME/.kube/config; sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: 创建 master join 脚本
  shell: "grep -B2 ' --certificate-key' {{ tmp_dir }}/token.txt > {{ tmp_dir }}/master-join.sh"

- name: 创建 node join 脚本
  shell: "grep -A1 'kubeadm join' {{ tmp_dir }}/token.txt |tail -2 > {{ tmp_dir }}/node-join.sh"

- name: 拷贝YAML文件到Master
  copy: src={{ item }} dest={{ tmp_dir }}
  with_items:
    - "calico.yaml"
#    - "custom-resources.yaml"

- name: 部署NIC Calico插件
  ignore_errors: yes
  shell: "kubectl apply -f calico.yaml"
  args:
    chdir: "{{ tmp_dir }}"
  
