---
- name: 创建临时目录
  file: dest={{ addons_dir }} state=directory

- name: 拷贝YAML文件到Master
  copy: src={{ item }} dest={{ addons_dir }}
  with_fileglob:
    - "*.yaml"

- name: 拷贝tls文件到Master
  copy: src={{ item }} dest={{ addons_dir }}
  with_fileglob:
    - "tls/*"

- name: 自签tls证书
  ignore_errors: yes
  shell:
    cmd: | 
      echo subjectAltName = IP:{{ vip }} > extfile.cnf
      /bin/bash tls.sh
  args:
    chdir: "{{ addons_dir }}"

- name: 部署Dashboard,Ingress-Nginx
  ignore_errors: yes
  shell: for yaml in $(ls *.yaml);do kubectl apply -f $yaml;done
  args:
    chdir: "{{ addons_dir }}"

- name: 创建自签tls证书secret
  shell: kubectl create secret generic kubernetes-dashboard-certs --from-file=tls.key=server.key --from-file=tls.crt=server.crt -n kubernetes-dashboard
  args:
    chdir: "{{ addons_dir }}"

- name: 获取Dashboard管理员令牌
  ignore_errors: yes
  shell: |
         web='https://{masterip/lvs-vip}:{{ admin_port }}'
         token=$(kubectl get secret -n kubernetes-dashboard `kubectl get secret -n kubernetes-dashboard |grep admin|awk '{print $1}'` -o yaml |grep token:|sed '$d'|awk '{print $2}' |base64 -d)
         echo "访问地址"
         echo "$web"
         echo "令牌内容"
         echo "$token" 
  register: ui
- name: Kubernetes Dashboard登录信息
  debug: var=ui.stdout_lines
