---
- name: install package
  package:
    name:
      - ntp
      - ntpdate
      - rsync
      - bash-completion
      - net-tools
      - wget
      - gcc
      - gcc-c++
      - lrzsz
      - vim
      - unzip
      - make
      - openssl-devel
      - iptables-services
    state: latest